### ISSUE TITLE
Make this private lol

### ISSUE THREAD

**Issue by ethanzh** [grant-he/CS103F#1]
Just wanna make sure u don't get in trouble for having your stuff public on github for this class

**Comment by grant-he** [comment]
Appreciate your concern. Private repositories cannot create a GitHub page, so I guess this is going to stay public. What makes this different from a WordPress website? (which is public through http anyway)

**Comment by ethanzh** [comment]
my bad, i totally didn't read that we were meant to have a public site. ur all good.
